version: '3.8'
services:
  hugo:
    build: ./hugo
    ports:
      - "1313:1313"
    networks:
      - mynetwork


  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - hugo
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
networks:
  mynetwork:
    driver : bridge
