version: '3.8'
services:
  hugo:
    container_name: hugo
    build: ./hugo
    restart: unless-stopped
    ports:
      - "1313:1313"
    networks:
      - mynetwork


  proxy:
    container_name: proxy
    build: ./proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - hugo
      - db
    networks:
      - mynetwork

  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - mynetwork
networks:
  mynetwork:
    driver : bridge
